services:
  - type: web
    name: numerologia-fullstack
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
        placeholder: "Tu URL de MongoDB Atlas"
      - key: SECRETORPRIVATEKEY
        generateValue: true
      - key: API_KEY
        sync: false
        placeholder: "Tu Gemini API Key 1"
      - key: ADMIN_SECRET_KEY
        value: Sena2026*Migue
      - key: EMAIL_USER
        value: respuestasnum@gmail.com
      - key: EMAIL_PASS
        value: uaylhepohaicecyx
      - key: CRON_SECRET_TOKEN
        generateValue: true
      - key: API_URL
        value: https://numerologia-fullstack.onrender.com/api
